import { MigrationInterface, QueryRunner } from 'typeorm';

export class UserRefactoringId1780931163251 implements MigrationInterface {
  name = 'UserRefactoringId1780931163251';

  public async up(queryRunner: QueryRunner): Promise<void> {
    const result = await queryRunner.query(
      `SELECT column_default, is_identity FROM information_schema.columns WHERE table_name = 'users' AND column_name = 'id'`,
    );
    const hasDefault = result[0]?.column_default !== null;
    const isIdentity = result[0]?.is_identity === 'YES';

    if (!hasDefault && !isIdentity) {
      await queryRunner.query(
        `ALTER TABLE "users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY`,
      );
    } else {
      console.log(
        'Ignoring error: column id of relation users already has a default value',
      );
    }
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "users" ALTER COLUMN "id" DROP IDENTITY IF EXISTS`,
    );
  }
}
