import { MigrationInterface, QueryRunner } from 'typeorm';

export class UserRefactoringId1780931163251 implements MigrationInterface {
  name = 'UserRefactoringId1780931163251';

  public async up(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "users" ALTER COLUMN "id" ADD GENERATED BY DEFAULT AS IDENTITY`,
    );
  }

  public async down(queryRunner: QueryRunner): Promise<void> {
    await queryRunner.query(
      `ALTER TABLE "users" ALTER COLUMN "id" DROP IDENTITY IF EXISTS`,
    );
  }
}
